name: Readme Update

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # 1시간에 한번씩 아래 스크립트를 실행.  
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          npm ci
          npm install rss-parser
      - name: Update README
        run: npm start
      - name: Commit README
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "5a6io"
          git add .
          git commit -m "Update README.md"
          git push origin main
